# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/transsion/mt6789-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mt6789-common)

endif
